version: '3.8'

services:
  web:
    build: .
    container_name: django-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env.production
    depends_on:
      - db
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000 --workers 3

  db:
    image: postgres:15-alpine
    container_name: django-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-myportfolio}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
    ports:
      - "5432:5432"

volumes:
  postgres_data: