# Generated by Django 5.2.7 on 2025-10-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g., react, python, django)', max_length=50)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Friendly URL')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('short_description', models.CharField(help_text='Shown in project cards', max_length=300, verbose_name='Short description')),
                ('body_html', models.TextField(help_text='Full project content using HTML', verbose_name='Body Content (HTML)')),
                ('title_es', models.CharField(max_length=200, verbose_name='Título (Español)')),
                ('short_description_es', models.CharField(help_text='Se muestra en las tarjetas de proyecto', max_length=300, verbose_name='Descripción corta (Español)')),
                ('body_html_es', models.TextField(help_text='Contenido completo del proyecto usando HTML', verbose_name='Cuerpo del contenido (HTML Español)')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('demo_url', models.URLField(blank=True, verbose_name='Demo URL')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='core.technology', verbose_name='Technologies')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-id'],
            },
        ),
    ]
