# Generated by Django 5.2.7 on 2025-10-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(null=True, verbose_name='Demo URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(null=True, verbose_name='GitHub URL'),
        ),
    ]
