# Generated by Django 5.2.7 on 2025-10-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_video_url_alter_project_demo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, default='', verbose_name='Demo URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(default='', verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, default='', verbose_name='Video URL'),
        ),
    ]
