# Generated by Django 5.2.7 on 2025-10-15 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_architecture_diagram_project_result_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='architecture_diagram',
        ),
        migrations.RemoveField(
            model_name='project',
            name='body_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='body_html_es',
        ),
        migrations.RemoveField(
            model_name='project',
            name='result_image',
        ),
        migrations.AddField(
            model_name='project',
            name='body_html_conclusion',
            field=models.TextField(blank=True, help_text='Final section - Results, learnings, future improvements', verbose_name='Conclusion (HTML)'),
        ),
        migrations.AddField(
            model_name='project',
            name='body_html_conclusion_es',
            field=models.TextField(blank=True, help_text='Sección final - Resultados, aprendizajes, mejoras futuras', verbose_name='Conclusión (HTML Español)'),
        ),
        migrations.AddField(
            model_name='project',
            name='body_html_intro',
            field=models.TextField(blank=True, help_text='First section - Overview, problem statement, context', verbose_name='Introduction (HTML)'),
        ),
        migrations.AddField(
            model_name='project',
            name='body_html_intro_es',
            field=models.TextField(blank=True, help_text='Primera sección - Resumen, problema, contexto', verbose_name='Introducción (HTML Español)'),
        ),
        migrations.AddField(
            model_name='project',
            name='body_html_middle',
            field=models.TextField(blank=True, help_text='Second section - Solution, implementation, technical details', verbose_name='Middle Content (HTML)'),
        ),
        migrations.AddField(
            model_name='project',
            name='body_html_middle_es',
            field=models.TextField(blank=True, help_text='Segunda sección - Solución, implementación, detalles técnicos', verbose_name='Contenido Medio (HTML Español)'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image_after_intro',
            field=models.ImageField(blank=True, help_text='Se muestra entre intro y middle section (ej: diagrama de arquitectura)', null=True, upload_to='projects/content/', verbose_name='Imagen después de Intro'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_after_middle',
            field=models.ImageField(blank=True, help_text='Se muestra entre middle y conclusion (ej: resultados, screenshots)', null=True, upload_to='projects/content/', verbose_name='Imagen después de Middle'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show in featured projects section', verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(help_text='Shown in project cards (listing view)', max_length=300, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description_es',
            field=models.CharField(help_text='Se muestra en las tarjetas de proyecto (vista de listado)', max_length=300, verbose_name='Descripción corta (Español)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Friendly URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Imagen para tarjeta en listado (Recomendado: 800x600px)', null=True, upload_to='projects/thumbnails/', verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='YouTube, Vimeo, etc.', verbose_name='Video URL'),
        ),
    ]
